should work

diff --git a/twitter_backup b/twitter_backup
--- a/twitter_backup
+++ b/twitter_backup
@@ -11,9 +11,16 @@ else
   else
     echo 'Installing'
     bash -s stable < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer)
-    source "~/.bash_profile"
-    rvm install 1.9.3
-    "$RUBY_EXEC" -x $0 $1 $2 $3
+    source ~/.rvm/scripts/rvm
+    rvm --default install 1.9.3
+    RUBY_EXEC=`which ruby`
+    if [ -n "$RUBY_EXEC" ]; then
+      "$RUBY_EXEC" -x $0 $1 $2 $3
+      exit $?
+    else
+      echo 'Ruby installation failed, please install manually.'
+      exit 2
+    fi
   fi
 fi
 
